### ISSUE TITLE
Glide为什么不升级啊 

### ISSUE THREAD

**Issue by ProfessionalMe** [KF5/KF5SDK-Andriod2.0#9]
我这里用的Glide4.5版本。但是KF5用的3.7  然后我用的时候就报错了。请问怎样解决？

java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/yufei99.com.yj-2/split_lib_dependencies_apk.apk)
                                                                  at com.kf5.sdk.system.utils.ImageLoaderManager.displayImage(ImageLoaderManager.java:62)
                                                                  at com.kf5.sdk.im.keyboard.widgets.EmoticonsToolBarView.initItemToolBtn(EmoticonsToolBarView.java:88)
                                                                  at com.kf5.sdk.im.keyboard.widgets.EmoticonsToolBarView.addToolItemView(EmoticonsToolBarView.java:133)
                                                                  at com.kf5.sdk.im.keyboard.widgets.EmoticonsToolBarView.addToolItemView(EmoticonsToolBarView.java:124)

**Comment by ChosenKing** [comment]
您好，请先手动升级一下glide版本号，考虑到glide版本差异化较大，暂时未升级，近期会做升级。

**Comment by ChosenKing** [comment]
closed #xxx
